[package]
name = "light-flash"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "light-flash"
harness = false # We can't use the default rust libtest harness for a crosscompile target

[profile.release]
opt-level = "s"

[profile.dev]
debug     = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]


[dependencies]
log = { version = "0.4", default-features = false}
rgb-led     = { path = "../common/lib/rgb-led" }
wifi_ap = { path = "../common/lib/wifi_ap" }
http_server = { path = "../common/lib/http_server" }
esp-idf-svc = { version = "=0.51"}
esp-idf-hal = { version = "=0.45"}
anyhow = "=1.0.95"
heapless ="0.8.0"

[build-dependencies]
embuild  = "=0.33.0"