[package]
name = "light-flash"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "light-flash"
harness = false # pas de harness libtest en cross-compilation

[dependencies]
anyhow.workspace = true
log.workspace = true
esp-idf-svc.workspace = true
light-core.workspace = true
rgb-led.workspace = true
wifi.workspace = true
storage.workspace = true
http-server.workspace = true
toml-cfg.workspace = true

[build-dependencies]
embuild.workspace = true

# Composants ESP-IDF supplémentaires (registre de composants Espressif). mDNS n'est plus livré
# avec ESP-IDF 5.x. Toute modification ici reconstruit ESP-IDF.
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/mdns", version = "1.2" }
